
CREATE TABLE OAUTH_CLIENT_DETAILS (
    CLIENT_ID VARCHAR(255) PRIMARY KEY,
    RESOURCE_IDS VARCHAR(255),
    CLIENT_SECRET VARCHAR(255),
    SCOPE VARCHAR(255),
    AUTHORIZED_GRANT_TYPES VARCHAR(255),
    WEB_SERVER_REDIRECT_URI VARCHAR(255),
    AUTHORITIES VARCHAR(255),
    ACCESS_TOKEN_VALIDITY INTEGER,
    REFRESH_TOKEN_VALIDITY INTEGER,
    ADDITIONAL_INFORMATION VARCHAR(4096),
    AUTOAPPROVE VARCHAR(255)
);

CREATE TABLE OAUTH_ACCESS_TOKEN (
    AUTHENTICATION_ID VARCHAR(255) PRIMARY KEY,
    TOKEN_ID VARCHAR(255),
    TOKEN BLOB,
    USER_NAME VARCHAR(255),
    CLIENT_ID VARCHAR(255),
    AUTHENTICATION BLOB,
    REFRESH_TOKEN VARCHAR(255)
);


CREATE TABLE OAUTH_CLIENT_TOKEN (
    AUTHENTICATION_ID VARCHAR(255) PRIMARY KEY,
    TOKEN_ID VARCHAR(255),
    TOKEN BLOB,
    USER_NAME VARCHAR(255),
    CLIENT_ID VARCHAR(255)
);


CREATE TABLE OAUTH_REFRESH_TOKEN (
    id int AUTO_INCREMENT,
    TOKEN_ID VARCHAR(255),
    TOKEN BLOB,
    AUTHENTICATION BLOB,
    PRIMARY KEY(id)
);

CREATE TABLE OAUTH_CODE (
    id int AUTO_INCREMENT,
    CODE VARCHAR(255),
    AUTHENTICATION BLOB,
    PRIMARY KEY(id)
);

CREATE TABLE OAUTH_APPROVALS (
    id int AUTO_INCREMENT,
    USERID VARCHAR(255),
    CLIENTID VARCHAR(255),
    SCOPE VARCHAR(255),
    STATUS VARCHAR(10),
    EXPIRESAT TIMESTAMP,
    LASTMODIFIEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);